### ISSUE TITLE
Json2Xml and Xml2Json

### ISSUE THREAD

**Issue by Suzii** [Suzii/pb138-cv_generator#3]
Create two interfaces providing a transformation from JSON to XML and vice versa. Strucute of JSON and XML are predefined and referencing files have to be strod in "Sample" directory of project. XML Schema has to be created as well and text file summarizing the required fields and allowed values have to be created for other developers

**Comment by petersvk** [comment]
Json -> XML is implemented in class Json2Xml and XML -> Json in class Xml2Json.
Both classes seam to be working. Now we need to test them.

**Comment by Suzii** [comment]
XML2Json contains a bug. When trying to convert an XML containing only one phone or email inside of aphones / emails element, exception org.json.JSONException: JSONObject["email"] is not a JSONArray. is thrown. When there are two element phone everthing seems to be ok.

**Comment by petersvk** [comment]
Fixed

**Comment by Suzii** [comment]
Modify XML Schema and both json2xml and xml2json to accomodate new XML structure. Changes:
- &lt;date-of-birth> now contains day, month, year elements
- &lt;computer-skills> level element deleted 
- &lt;language-skills> enum is A1, A2, B1, B2, C1, C2

**Comment by petersvk** [comment]
done
